import './globals.css'
import type { Metadata } from 'next'
import { Urbanist } from 'next/font/google'

import { Footer } from '@/components/non-reusable/footer'
import { Navbar } from '@/components/non-reusable/navbar/'
import ModalProvider from '@/provider/modal-provider'
import ToastProvider from '@/provider/toast-provider'

const urbanist = Urbanist( { subsets: [ 'latin' ] } )

export const metadata: Metadata = {
  title: 'Store Project',
  description: 'Generated by Store',
}

export default function RootLayout ( {
  children,
}: {
  children: React.ReactNode
} )
{
  return (
    <html lang="en">
      <body className={ urbanist.className }>
        <ModalProvider />
        <ToastProvider />
        <Navbar />
        { children }
        <Footer />
      </body>
    </html>
  )
}
