import './globals.css'
import type { Metadata } from 'next'
import { Urbanist } from 'next/font/google'

import { Footer } from '@/components/non-reusable/footer'
import { Navbar } from '@/components/non-reusable/navbar/'
import ModalProvider from '@/providers/modal-provider'
import ToastProvider from '@/providers/toast-provider'
import { ThemeProvider } from '@/providers/theme-provider'

const urbanist = Urbanist( { subsets: [ 'latin' ] } )

export const metadata: Metadata = {
  title: 'Store Project',
  description: 'Generated by Store',
}

export default function RootLayout ( {
  children,
}: {
  children: React.ReactNode
} )
{
  return (
    <html lang="en">
      <body className={ urbanist.className }>
        <ThemeProvider attribute='class' defaultTheme='dark' enableSystem>
          <main className='flex flex-col justify-between h-[100vh]'>
            <div>
              <ModalProvider />
              <ToastProvider />
              <Navbar />
              { children }
            </div>
            <Footer />
          </main>
        </ThemeProvider>
      </body>
    </html>
  )
}
