import './globals.css'
import type { Metadata } from 'next'
import { Urbanist } from 'next/font/google'

import { Footer } from '@/components/non-reusable/footer'
import { Navbar } from '@/components/non-reusable/nav/navbar'

const urbanist = Urbanist( { subsets: [ 'latin' ] } )

export const metadata: Metadata = {
  title: 'store',
  description: 'Generated by store',
}

export default function RootLayout ( {
  children,
}: {
  children: React.ReactNode
} )
{
  return (
    <html lang="en">
      <body className={ urbanist.className }>
        <Navbar />
        { children }
        <Footer />
      </body>
    </html>
  )
}
